language: java
jdk:
  - openjdk8

services:
  - docker

after_script:
  - mvn package
  - docker build -t snowch/db-demo .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
